### ISSUE TITLE
sam  file parser  wrong?

### ISSUE THREAD

**Issue by jameslz** [qiyunzhu/woltka#144]
woltka classify for align/bowtie2/S01.sam.xz

```
woltka classify  --to-tsv  -f sam   -i  S01.sam --digits 4   -o   sam.txt
```

- logs 

    Input alignment file: S01.sam.
    Demultiplexing: off.
    Classification will operate on these ranks: none.
    Parsing alignment file S01.sam . Done.
      Number of sequences classified: 2000.
    Classification completed.
    Format of output feature table(s): TSV.
    Writing output profiles in TSV format...
      Rank: none, samples: 1, features: 8.
    Profiles written.
    Task completed.

-  query/reference map

```
samtools view  S01.sam | cut -f1,3  > S01.map
woltka classify  --to-tsv -f map -i  S01.map --digits 4   -o   map.txt
```

- logs 

    Input alignment file: S01.map.
    Demultiplexing: on.
    Classification will operate on these ranks: none.
    Parsing alignment file S01.map . Done.
      Number of sequences classified: 1000.
    Classification completed.
    Format of output feature table(s): TSV.
    Writing output profiles in TSV format...
      Rank: none, samples: 1, features: 8.
    Profiles written.
    Task completed.

using `sam` and `map` file format get difference result.

**Comment by qiyunzhu** [comment]
Hello @jameslz Thanks for your interest and report. The reason is: When you analyze the original SAM files, Woltka will automatically recognize the paired-end information. For example: "ReadX 64" and "ReadX 128" (number is the SAM flag) will become "ReadX/1" and "ReadX/2" after processing. For a simple mapping file, this information is not retained, and the two reads will be merged into "ReadX". Therefore you got half the number of reads when you process the mapping file.

**Comment by jameslz** [comment]
Thank you for your reply. I get the sam result after add paired-end information.

```
samtools view  S01.sam  | ./ogu-tk sam2map - | ./ogu-tk classify - 
```

and I get

```
#FeatureID      counts
G000091545      1614.0000
G000015005      176.0000
G000011705      132.0000
G000011545      48.0000
G000185905      4.0000
G000007785      12.0000
G000018865      12.0000
G000240185      2.0000
```

The map format may be a good  solution.
