### ISSUE TITLE
.partition("\t")[0] is faster than .split("\t", 1)[0]

### ISSUE THREAD

**Issue by gwarmstrong** [qiyunzhu/woltka#8]
https://github.com/qiyunzhu/woltka/blob/862cab09e3da201cf8db20b4968849950fcc0fd5/woltka/util.py#L251

For some reason using `.partition` in this use case is a bit faster than `.split`.

Here is a relevant stackoverflow thread: https://stackoverflow.com/questions/27387415/how-would-i-get-everything-before-a-in-a-string-python/27387468

Note that I don't think the pre-compiled regex holds in this case...

And here is a small benchmark on my machine to corroborate the thread

```
In [1]: %timeit "abadfaef\tasfaegaa".strip().partition("\t")[0]
261 ns ± 5.58 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [2]: %timeit "abadfaef\tasfaegaa".strip().split("\t", 1)[0]
375 ns ± 5.64 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```

**Comment by qiyunzhu** [comment]
Thank you for noting this! In this particular place, performance is not important. But it is potentially useful in multiple other places where performance is critical. This motivated me to change this as well as the other places, such as `demultiplex` and in `classify.py`. Commit [c188d1f](https://github.com/qiyunzhu/woltka/commit/c188d1fad2b1dcba6f2466f95032c7f5af840bf8).

PS: I hope that we upgrade to Python 3.8 so that we can use the warlus operator who seems to be more neat in this case.
